### ISSUE TITLE
 NAM 1975 NO SOUND

### ISSUE THREAD

**Issue by OBurgerGuy** [libretro/fbalpha#172] opened 2019-03-08 23:06 UTC
running lr-fba v0.2.97.44 2def8e5 with matching romset, under retroarch v1.7.6 running retropie v4.4.8: neo-geo nam 1975 produces no sound after coin inserted and game starts... prior to coin insertion there is attract sound.

**Comment by dinkc64** [comment] 2019-03-09 02:19
This happened before, but I can't remember what the problem or the solution was.  :(
@barbudreadmon any ideas? :)

**Comment by dinkc64** [comment] 2019-03-09 02:39
@barbudreadmon, ignore that.  I did some research on the forum and noticed that the issue was talked about, but never fixed.
I added a test-fix.  it fixes nam-1975 with any bios selected now, but, other games need testing - would you (or anyone) mind testing some random neogeo games to make sure there aren't any issues?

**Comment by dinkc64** [comment] 2019-03-09 02:40
@OBurgerGuy thanks for the bug report, a fix should be available for the libretro core soon! :)

**Comment by OBurgerGuy** [comment] 2019-03-09 04:32
thanks for PROMPT attention, you rock!

**Comment by OBurgerGuy** [comment] 2019-03-09 05:22
> @barbudreadmon, ignore that. I did some research on the forum and noticed that the issue was talked about, but never fixed.
> I added a test-fix. it fixes nam-1975 with any bios selected now, but, other games need testing - would you (or anyone) mind testing some random neogeo games to make sure there aren't any issues?

will test "problem children" roms known to cause issues during updates, i restored neo-geo conversion cab and put pi in it for mvs-only action :)

**Comment by barbudreadmon** [comment] 2019-03-09 07:16
@dinkc64 i digged the first issue : https://github.com/barbudreadmon/fbalpha2018/issues/163, you might find what fix was applied the first time if you look at 2017-12 changes.

**Comment by OBurgerGuy** [comment] 2019-03-09 07:25
Baseball Stars Professional no audio after coin inert, girls dont speak, same as before.. same conditions

**Comment by barbudreadmon** [comment] 2019-03-09 07:29
@OBurgerGuy You are already using 854c97fa3d1a862545a9674b5e4f147058c4c7ba ??? I only merged the fix a few minutes ago

**Comment by OBurgerGuy** [comment] 2019-03-09 07:38
literally just tested it, the update from source finished 15 minutes ago

**Comment by OBurgerGuy** [comment] 2019-03-09 07:40
still 2def8e5, will update again

**Comment by barbudreadmon** [comment] 2019-03-09 07:45
@OBurgerGuy don't jump the gun, check things carefully before posting new informations, try not to post several new messages in a row.

@dinkc64 i won't be at home today, so feel free to merge any further fix into the libretro fork without me.

**Comment by dinkc64** [comment] 2019-03-09 14:03
@OBurgerGuy 
Baseball stars appears to be working fine after this fix on my side,  Please try again with the latest code from git :)  If you're just updating the core inside retroarch it might take a day or so before the updated core is available.  (I'm not sure exactly the logistics of it all)

best regards,
- dink

**Comment by OBurgerGuy** [comment] 2019-03-09 15:37
BSP and NAM 1975 work perfectly...

**Comment by dinkc64** [comment] 2019-03-09 23:24
Glad to hear it! :)  Thanks again for the bug report,

best regards,
- dink

**Comment by barbudreadmon** [comment] 2019-03-12 18:19
@dinkc64 reopening this issue, i think the fix might have caused some regression in other games, see https://forums.libretro.com/t/fb-alpha-bugs-with-unibios/21318

I can also reproduce the issue in sonicwi3 with standard MVS bios, just by pressing coin a lot on the title screen.

**Comment by dinkc64** [comment] 2019-03-12 22:57
Nice find!  It turns out that this is actually a regression from the neogeocd re-re-re-work - oops! :)  fix will be available soon.

**Comment by dinkc64** [comment] 2019-03-13 00:37
The controller issue in unibios w/aes mode in Metal Slug 3&4 isn't caused by anything I did recently, but I'll try to fix that and post progress on it here.
The audio issue with sonicwi3 is definitely a regression from the ngcd rework, though.  A fix for at least that will be availble tonight :)

**Comment by dinkc64** [comment] 2019-03-13 02:09
news: the controller issue that happens when selecting console(AES) mode via the Unibios in metal slug3/4 isn't a bug in the emulation.
From the Unibios homepage "Known Issues":
Later games in the Metal Slug and Samurai Shodown series (MS X,3,4,5 and SS 4,5,5Sp) may not work correctly in console mode until after you have set up the game settings and controller config in the options menu (after starting a game). This problem is due to the games not setting up the initial backup ram data correctly for console mode if the game is first run on the system while it is in ARCADE mode (you must experience a 'GAME OVER' before the new settings are permanently saved).

**Comment by dinkc64** [comment] 2019-03-13 03:09
A fix for sonicwi3 is in the main branch.

**Comment by barbudreadmon** [comment] 2019-03-13 07:44
Thanks :)

**Closed by barbudreadmon** 2019-03-13 07:44 UTC
Labels: FOR DINK, bug
