### ISSUE TITLE
Raiga Strato Fighter (stratof) - Transparencies not rendered correctly

### ISSUE THREAD

**Issue by dankcushions** [libretro/fbalpha#104] opened 2016-10-30 23:38 UTC
The pink 'goo' in level 3 is rendered as a solid pink, rather than the correct translucent pink as shown in this video:

https://www.youtube.com/watch?v=VB3QiJPjkkY&feature=youtu.be&t=454

this is a problem as it means you can't see your ship, or enemies/bullets in these areas :) I've also attached a save-state for the problem: [stratof.state.zip](https://github.com/libretro/fbalpha/files/560858/stratof.state.zip)

This might be an upstream bug, but I have no means of testing standard FBA.

**Comment by barbudreadmon** [comment] 2016-11-01 07:48
I checked, libretro-fbalpha ignore transparency (there is an alpha which is totally ignored by our function), not sure how am i supposed to deal with that.

**Comment by dankcushions** [comment] 2016-11-01 10:30
interesting! does this happen with EVERY fbalpha game with alpha? i'm not too sure either but maybe it's something to do with the retro_pixel_format

https://github.com/libretro/fbalpha/blob/3a02d6e854e271fcddc7cb4eca08a3e148ca72c7/src/burner/libretro/libretro.cpp#L1545

https://github.com/libretro/fbalpha/blob/9b089dc5cdb437f54667ba53766ad18bc7d49500/src/burner/libretro/libretro.h#L1848

**Comment by barbudreadmon** [comment] 2016-11-01 11:40
I think so, but i don't know much about retro_pixel_format, i'll try to figure out something later.

**Comment by sergiobenrocha2** [comment] 2017-04-19 02:59
Still an issue on 0.9.27.40

The save state:

![stratof state](https://cloud.githubusercontent.com/assets/5431285/25161555/099acadc-2493-11e7-9314-3025363e12fb.png)

**Comment by barbudreadmon** [comment] 2017-04-29 08:48
I tried to rework how libretro-fbalpha handle rendering to be more "upstream-like", but it didn't solve this issue, so it could be an upstream bug.

**Comment by barbudreadmon** [comment] 2017-04-30 07:06
I confirm the upstream bug, i reported it : http://neosource.1emulation.com/forums/index.php?topic=1731.msg23834#msg23834

**Comment by barbudreadmon** [comment] 2017-04-30 13:30
Answer from dink : 

> At the present time, our Raiga emulation doesn't support alpha blending or raster effects.  (that's why the title flickers horribly).

There won't be a quick fix for this, you'll have to wait patiently until it is added to an upstream release.
Since this is not a bug with the port, i close.

**Comment by dankcushions** [comment] 2017-04-30 20:26
Thanks for testing upstream and reporting it :)

**Comment by dankcushions** [comment] 2017-07-12 10:07
this is apparently fixed in .41/.42 upstream :dancer: 

https://www.fbalpha.com/view/237/

**Comment by barbudreadmon** [comment] 2017-07-13 12:13
I'll bump to .42 this week-end. Didn't notice it was released last week-end (and i would have been short on time anyway)

**Closed** 2017-08-13 06:13 UTC
