### ISSUE TITLE
Zero team on Wii U show only garbage on screen

### ISSUE THREAD

**Issue by cecilmax** [libretro/fbalpha#211] opened 2018-05-22 03:25 UTC
When I run Zero Team on Wii U the game start and I can insert coin and start the game but the graphics are complete maze, garbage on screen ....

**Comment by barbudreadmon** [comment] 2018-05-22 05:48
Could be an endianess issue ? Post a screenshot please.

**Comment by barbudreadmon** [comment] 2018-05-22 06:09
I'm also interested in how raiden 2 runs, especially the first level boss (see https://github.com/libretro/fbalpha/issues/198).

@fr500 Beside endianness, is there anything particular to know about ppc and wii u ? float to int conversion ? math library ? The raiden2/zeroteam driver uses a lot of math and float to int conversion.

**Comment by cecilmax** [comment] 2018-05-22 10:29
Here the screenshot :)

https://pasteboard.co/HmleZOq.jpg

**Comment by barbudreadmon** [comment] 2018-05-22 10:36
Thanks, i have seen similar issues in some drivers in the past, they were quickly fixed with the help of upstream. Same in raiden2 i guess ?

**Comment by cecilmax** [comment] 2018-05-22 11:43
I dont know about raiden2, I didnt try it :)

If you can tell me once it is fixed I can test both :)

**Comment by barbudreadmon** [comment] 2018-05-22 11:59
I need to know if raiden2 have this issue to figure out if the issue is within the driver code or the game code.
Also, trying dynduke, raiden, rtype and rtype2 would help ruling out an issue in the cpu code.

**Comment by cecilmax** [comment] 2018-05-22 13:28
Ok I will test it tonight and let you know :)

**Comment by cecilmax** [comment] 2018-05-23 00:27
Raiden1 work fine to and rtype2 too

**Comment by barbudreadmon** [comment] 2018-05-23 05:31
What about raiden2 ? This is the most important one to test...

**Comment by cecilmax** [comment] 2018-05-23 11:42
I have posted a link to a screenshot about graphics issue in D.D crew too, that game also have graphics issue, not only audio, if you can reopen the ticket please :)

**Comment by cecilmax** [comment] 2018-05-23 11:43
Let me check for raiden2, I didnt find a rom yet that work, maybe I need another romset.. Ill try it again tonight.

**Comment by barbudreadmon** [comment] 2018-05-23 12:02
On https://github.com/libretro/fbalpha : 
> Use clrmamepro (which run fine on linux with wine and macos with crossover) to build valid romsets with dats from the dats directory. fba dats are NOT mame dats. Don't report issues if you didn't build a valid romset.

The fact you weren't answering my question was already pissing me off, now you are saying your issues could be related to bad roms downloaded randomly on internet. Because of that i can't trust any of your reports. Thanks for making me lose my time.

**Comment by cecilmax** [comment] 2018-05-23 12:15
Are you serious ? Wow! I took time to share bugs to try to help other to enjoy this core by helping fixing it and I am the one wasting your time ? Incredible. Sorry you take it like that. I will try to fix it on my own. For your information, I have a valid romset but sometime, with a valid romset it happen that somes games just doesnt load..

**Comment by barbudreadmon** [comment] 2018-05-23 12:29
> with a valid romset it happen that somes games just doesnt load..
no

**Comment by cecilmax** [comment] 2018-05-23 12:39
Well, I already checked raiden2 with crlmamepro and the game just doesnt load. And that is not the only game that happen. And when I try another source where I find the rom it work. I dont say youre not right I just explain my situation. Anyway, it is useless if you dont care fixing your project. Thanks for your time.

**Comment by barbudreadmon** [comment] 2018-05-23 12:47
It is useless if you use another rom, the program is written to run with a specific version of a rom, if you write a report with another version of the rom, it has no value.
If the expected rom of raiden2 doesn't work, you should have said that from the start. Since zeroteam is from the same driver, that means the expected rom of zeroteam probably doesn't work, and you are using another one, hence your graphical issues. If you change rom to another version and worse : **don't mention it**, your reports have no value.

Want to make something not useless ? Use official rom and tell me what's happening with the official rom.

**Comment by cecilmax** [comment] 2018-05-23 12:55
ok, let me check that and I let you know if raiden2 have the same graphic issue.

**Comment by barbudreadmon** [comment] 2018-05-23 13:13
Just make sure you are using official roms, for every report, and tell me what's happening, even if you got a black screen or the emulator crashes. If i try to fix issues which happens with other versions of the rom, things will turn worse.

**Comment by barbudreadmon** [comment] 2018-05-23 13:17
Also, sorry i snapped. I've seen too many people reporting issues with bad roms, and now i have zero tolerance for this.

**Comment by cecilmax** [comment] 2018-05-23 15:21
No problem :)

What do you think of d.d crew graphic issue ? Does it worth a try to investigate ? Ive post a screenshot of the issue on the closed thread.

**Comment by cecilmax** [comment] 2018-05-23 16:14
Sure is :) dont worry.

**Comment by cecilmax** [comment] 2018-05-23 19:45
One more information: both games, zero team and dd crew are working fine under windows with fba 0.2.97.43 with the sames roms of course, so it must be something with the drivers or wii U implementation, maybe the float as you suggested above..

**Comment by cecilmax** [comment] 2018-05-24 00:54
Ok I just test it (raiden2), the game load with this garbage graphic on sceeen. I can insert coin but thats all, pressing buttons to start do nothing.
https://pasteboard.co/HmAkvvL.jpg

**Comment by barbudreadmon** [comment] 2018-05-24 06:45
Let's see if it's a big endian issue, try to rebuild the core with my latest commit.

**Comment by barbudreadmon** [comment] 2018-05-24 14:34
I am a linux user, i don't have any of the alternate devkits to build for other platforms.
It seems to me like the buildbot updated the fbalpha nightlies with my commits : http://buildbot.libretro.com/nightly/nintendo/wiiu/latest/fbalpha_libretro.rpx.zip

**Comment by cecilmax** [comment] 2018-05-24 15:03
Ah ok, I will try it tonight and let you know the result :)

**Comment by cecilmax** [comment] 2018-05-24 23:13
Just test zeroteam, no more garbage as previous but still a mess lol and the graphics are in the wrong colors, see:
https://pasteboard.co/HmJ4UTG.jpg

https://pasteboard.co/HmJ5zIh.jpg

And when the game start, there is no charcaters to move..

See:
https://pasteboard.co/HmJ64FJ.jpg

Tested raiden2: only show a black screen with a square of garbage color top right, I can insert coin and thats all I can do. Stuck there.

**Comment by barbudreadmon** [comment] 2018-05-25 05:57
Ok, at the very least it seems better than before.
Buildbot should update the nightly shortly, try the new version then post the new screenshots.

**Comment by barbudreadmon** [comment] 2018-05-25 08:10
I'll also tag @arcadez for this issue, he should be interested for his xbox fba port.

**Comment by dinkc64** [comment] 2018-05-25 12:38
xbox is le, no problem there.

**Comment by cecilmax** [comment] 2018-05-25 13:44
Here the new test, almost there :)

Zeroteam
https://pasteboard.co/HmONYTB.jpg
https://pasteboard.co/HmOOeUD.jpg

Raiden2
https://pasteboard.co/HmOOAXD.jpg

**Comment by dinkc64** [comment] 2018-05-27 03:40
cecilmax thank you very much for the images, I will have a final fix ready within the next day or so :)  
I just need to know one thing: can the game be coined up / started?

**Comment by cecilmax** [comment] 2018-05-27 05:45
For zeroteam it can be coined started, for raiden2, only coined..

**Comment by dinkc64** [comment] 2018-05-27 12:15
Thanks, without your help we would not be able to fix this since we have no BE-cpu machines to work with..  A version with possibly fixed sprites will be available shortly.  The amount of code that we need to go through for this emulation is quite massive, so please bear with us.

**Comment by cecilmax** [comment] 2018-05-27 15:08
No problem, Im very happy to help :) After this I can test other games too, does many games can be affected by this ?

**Comment by barbudreadmon** [comment] 2018-05-27 17:01
fbalpha is not written for big endian architecture. At some point there were active developpers (like @CaptainCPS) for ps3/xbox360 (which are also big endian machines) ports of fbalpha, but we don't see them a lot those days.
To be honest, it's probably affecting hundreds of games, mostly stuff from the last 5 years i would say.

**Comment by barbudreadmon** [comment] 2018-05-28 06:00
Let us know what is the result of the last 2 fixes. If everything is ok with zeroteam/raiden2, could you try dynduke again before moving to the ddcrew issue ?

**Comment by cecilmax** [comment] 2018-05-28 12:03
Ok Ill test it tonight :)

**Comment by cecilmax** [comment] 2018-05-28 23:12
Here is the results :)

raiden1: work perfectly, played 5 min
raiden2: work perfectly, played 5 min

rtype1 and rtype2: game load, show on black screen centered: rom ok, ram ok
Stuck there...

dynduke: game doesnt load at all: just return to retroarch..

Zeroteam: game load directly in I/O test screen..

**Comment by dinkc64** [comment] 2018-05-29 03:53
good news about raiden 1 and 2 :)  did raiden1 just start working with this update?
also very important: did rtype1, rtype2 and dynduke work before this last update?

thanks for your help,
best regards,
- dink

**Comment by barbudreadmon** [comment] 2018-05-29 05:42
> I just try dynduke and it have the same graphics garbage issue, I can insert coin, press start, sound seem ok, but its a real garbage display on screen :)
I try rtype and the graphics and sound are 100% ok.

It seems rtype did work before the update.

**Comment by cecilmax** [comment] 2018-05-29 06:58
Yes rtype work before the update

**Comment by cecilmax** [comment] 2018-05-29 07:01
Rtype1 and rtype2 work before the update and dynduke show garbage on screen before the update and now it doesnt load...

**Comment by dinkc64** [comment] 2018-05-29 11:21
Thanks for testing, even a bad result is going to be helpful to getting things right.  Bare with me here :)

**Comment by barbudreadmon** [comment] 2018-05-29 11:48
I reverted the changes on the nec cpu, let me know how the raidens, rtypes, and zeroteam work now.

**Comment by cecilmax** [comment] 2018-05-29 12:44
Ok :) ill test it after work ;)

**Comment by dinkc64** [comment] 2018-05-29 15:10
I also made some fixes to dynduke, they should be in sometime later today I hope.

**Comment by cecilmax** [comment] 2018-05-29 22:53
Ok here is the new results :)
raiden1: work perfectly
raiden2: now boot directly into diagnostic mode...
zeroteam: still boot ditectly into I/O test screen.
rtype1 and rtype2: still stuck on black screen with text: Rom ok ram ok centeted
dynduke: doesnt boot at all..

**Comment by barbudreadmon** [comment] 2018-05-30 02:39
> rtype1 and rtype2: still stuck on black screen with text: Rom ok ram ok centeted

That's not good at all, we reverted all changes affecting them so the code running them is exactly the same as when you said they were working, are you 100% sure they were working the first time you tried them ? Do you have an old copy of fbalpha wii u to check them again ?

**Comment by barbudreadmon** [comment] 2018-05-30 07:28
@cecilmax Either you didn't test rtypes properly the first time, or you used bad roms which worked for whatever reason... there is no way they would stop working when there was no change to the code running them...

So : 
* i pushed back the endian stuff to the nec cpu, @dinkc64 is right, that should be needed, and that should fix raiden2 (again). 
* i changed something in the macro handling byteswapping for wii u (the code could be slower, let me know if it seems to impact performance in games globally, we'll eventually revert back to the previous code after we are done debugging)
* i pushed some potential fixes for zeroteam

Let me know how things turns out.

**Comment by cecilmax** [comment] 2018-05-30 10:41
Ok ill make another batch of test tonight :)

**Comment by cecilmax** [comment] 2018-05-30 11:14
Ok, I just run another batch of test before going to work and here is the results:

now each game working 100%, run well, sound ok, played for 2-3 min each. BUT I discover something strange, that is what false my previous test.

This time I test them by restart retroarch each time before loading each game, in that case, each game work 100% with the lastest fixes.

If I load games in that order without restarting retroarch between each load, that mean I just quit the first game, choose close content et load another game, the 3rd game I load it load into a test mode or diagnostic mode or rtype1 or rtype2 stuck on the screen: rom ok, ram ok ...

its not seem to be specific to a game, whatever the order I choose to load each game one after another, after I load the 2nd game without restart retroarch the 3rd game doesnt load (if it is rtype it get stuck on screen ram ok, rom ok screen) if it is zeroteam of raiden2 it get stuck on test screen ...

Question: could it be a bug of Retroarch itself for this part ?

Finally, the results are perfect, theses games are fixed :)

**Comment by dinkc64** [comment] 2018-05-30 11:17
wow, this is great news :)  I think there is an underlying bug in retroarch for wii-u which is causing the games to fail when loaded after each other, like it isn't unloading the core to revert the variables, or something along those lines.  Thanks for helping with the tests, now the emulation is fine, we just need to find someone responsible for the retroarch core loader and see if they can fix it.

best regards,
- dink

**Comment by barbudreadmon** [comment] 2018-05-30 11:22
I'll check if i can reproduce this issue with my x86 setup, perhaps i'm not closing games properly.

**Comment by cecilmax** [comment] 2018-05-30 11:39
My pleasure :) Im very glad to help. You guys, do you know someone on the retroarch side to fix that bug or if I should open an issue ? Whats the best ?

**Comment by dinkc64** [comment] 2018-05-30 12:06
barbudreadmon: we also need to have a test done w/the original endian macros :)

**Comment by dinkc64** [comment] 2018-05-30 13:11
cecilmax, lets see what barbudreadmon finds out first.  then we'll go from there :)
also just a tip: for gameplay try new zeroteam or zero team 2000, as they are properly emulated games.  the original "zero team" has protection issues, and probably will never be emulated properly until someone decaps that protection chip and figures things out all the way.

**Comment by cecilmax** [comment] 2018-05-30 13:52
Ok ;) Ill test new zeroteam and zeroteam 2000 tonight.

**Comment by cecilmax** [comment] 2018-05-30 23:51
I just test all games again: rtype1, rtype2, raiden1, raiden2, dynduke and new zeroteam and zeroteam 2000 and all work 100% :)

**Comment by dinkc64** [comment] 2018-05-31 02:06
Thanks buddy :)

**Comment by cecilmax** [comment] 2018-05-31 03:06
There is maybe other games affected by be, I can test games that I like and doesnt work, should I create a different issue for each game or just one issue with a list ?

**Comment by barbudreadmon** [comment] 2018-05-31 05:44
I prefer you open an issue every time you find one, it will be easier to track it. I close this one.

**Closed** 2018-05-31 05:45 UTC

**Comment by barbudreadmon** [comment] 2018-06-01 07:59
> If I load games in that order without restarting retroarch between each load, that mean I just quit the first game, choose close content et load another game, the 3rd game I load it load into a test mode or diagnostic mode or rtype1 or rtype2 stuck on the screen: rom ok, ram ok ...

I think this issue should be solved with my latest commit, let me know if it's still happening.
