### ISSUE TITLE
Running Blazing Star (NEOGEO) on lr-fbalpha (no sound/music on end stage bosses)

### ISSUE THREAD

**Issue by Chogin** [libretro/fbalpha#137] opened 2017-05-11 17:54 UTC
Pi Model: 3 B

RetroPie Version Used: 4.2.5

USB Devices connected: None

Controller used: Wii U Pro Controller

Error messages received: All my NEOGEO games run flawlessly with lr-fbalpha except this one. When i reach the 1st boss of the game i simply loose the sound and music (with the exception of the insert coin sound). After i defeat the 1st boss and pass to the second stage sound and music are back until i reach the boss at the end of the level and once again exact same issue (no sound or music...). This is bizarre since it only happens 90% of the time. Every now and then i am able to get sound on those boss fights. If i use Mame2003, Mame2010 or lr-fbalpha 2012 i don't have this sound issues but on the other hand all those emulators have a graphical glitch where your ship cannot touch the left side of the screen and this has been fixed on the lr-fbalpha since version v0.2.97.38.

Emulator: lr-fbalpha v0.2.97.40

How to replicate the problem: happens 9 out of 10 times that i reach the boss at stage 1 (it only takes like 1 minute to reach that boss so it is pretty easy to check if this happens to you)

**Comment by barbudreadmon** [comment] 2017-08-13 06:55
I don't know if it was fixed with one of the recent commit, or if you have a setup issue, but i can't reproduce this bug myself (i'm using the latest core ofc). Do you still have this issue ?

**Comment by barbudreadmon** [comment] 2017-08-19 11:06
No answer, i close.

**Closed by barbudreadmon** 2017-08-19 11:06 UTC
