### ISSUE TITLE
Slowdown on CPS3 games

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/fbalpha#188] opened 2019-03-20 03:00 UTC
I use an OUYA to run retroarch.

In previous versions of the core, both CPS and NEOGEO games ran at full speed, 60 FPS, but now CPS3 have a lot of slowdown, running around 45 ~ 55 FPS, any game.

SNES, MEGA, PS ONE, etc... All other system are fine, only CPS 3 show this problem.

**Comment by barbudreadmon** [comment] 2019-03-20 05:54
Due to some fix 6 months ago, cps3 driver now needs slightly better hardware, i'm surprised your ouya thingy is slower than a rpi3b+ though.
Afaik, all of the slowdown comes from the rendering code so setting frameskip in core option to 1 should help a lot.

Closing, this is not a bug, there won't be a fix, and there is no workaround besides frameskip.

**Closed by barbudreadmon** 2019-03-20 05:54 UTC
