### ISSUE TITLE
Savestates don't work between sessions

### ISSUE THREAD

**Issue by GregorR** [libretro/fbalpha#92] opened 2016-09-28 02:02 UTC
I can save and load states while running the fbalpha core, but if I close RetroArch, restart it and attempt to load the state, it segfaults. If I had to venture a guess (and I do), I'd say that some pointers are accidentally being saved into the savestate.

(Discovered while testing netplay compatibility. Netplay peers segfault upon receiving remote savestates as well.)

**Comment by barbudreadmon** [comment] 2016-09-28 18:13
Seems you know what could be the issue, so feel free to push a merge request if you find a workaround.
Since this is a duplicate of #76 , i'll close this one.

**Closed by barbudreadmon** 2016-09-28 18:13 UTC
Labels: duplicate
