### ISSUE TITLE
FBA Alpha 0.2.97.42 : Riding Hero slow down in AES mode

### ISSUE THREAD

**Issue by j2k15** [libretro/fbalpha#165] opened 2017-12-18 23:02 UTC
Hi,

I observed big slowdowns for game Riding Hero (both sets) when run in AES mode.
The intro already has issue as well as the main menu.
I read that this might be related to the emulation of the "link" feature which would cause the issue.

**Comment by barbudreadmon** [comment] 2017-12-25 08:02
Hmm there is actually a fix for this issue, but it needs the cheat feature which is not yet implemented in this core.
See http://neo-source.com/index.php?topic=556.msg4722#msg4722

I'll close this bug since this is more or less a duplicate of #135

**Closed by barbudreadmon** 2017-12-25 08:02 UTC
Labels: enhancement

**Comment by j2k15** [comment] 2017-12-27 12:13
Hi,

In my opinion, this is not because a work-around does exist that the issue can be considered as closed since a structural solution is not in place.

And it's defnitely not a duplicate of #145 which is about adding the "cheat code feature" (in this case, it'd mean add the possibility to use the work-around in this core) while this one is about a slow-down in a specific game.

Anyway, I'm not the owner of this repo and not really play this game quite often, I've just created this issue because I observe an incompability with a game. My end goal is that this issue could be solved properly and this increase the quality of this great core.

Even if no one would work on this any soon, it shall be kept open to track it and keep in mind that a structural solution shall be found for this issue.

Have a great 2018 !

**Comment by barbudreadmon** [comment] 2017-12-27 13:08
How about asking upstream for a proper fix then ? It's not as if it was really a lr-fbalpha issue : it's an upstream issue with a known workaround which is to use cheats, the issue in lr-fbalpha is that the cheats are not implemented, so it is a duplicate.

I think a proper fix would already be included if it was possible, it's not as if they didn't know about this nor already worked on it, if you take a look at the post, you'll see there is an alternative method which cause crc issues, it also seems to be a known issue in mame. Personally I don't want to bother them for something they already know about.

**Comment by barbudreadmon** [comment] 2017-12-28 14:56
Btw, don't bother asking them, i did and i was right.

**Comment by j2k15** [comment] 2018-01-06 22:30
With Unibios it’s possisble to introduce cheats.
Do you have the cheat code which fixes the issue ?

So you mean that upstream they are not considering having a structural fix and that they are pleased with the workaround ? Thanks for having taken the initiative to ask them.

**Comment by barbudreadmon** [comment] 2018-01-07 02:13
No, i mean the only structural fix would break the compatibility of this game with unibios. I suppose the cheat code is somewhere in the file from the topic i mentioned.
