### ISSUE TITLE
No music with Neo Geo CD games?

### ISSUE THREAD

**Issue by bslenul** [libretro/fbalpha#231] opened 2018-08-21 11:31 UTC
Hey!

I tested 2 Neo Geo CD games in cue/iso/wav format (3 Count Bout/Fire Suplex and Choutetsu Brikin'ger/Ironclad), the games work fine but there's no music :(

`[libretro ERROR] *** Switching CD mode to audio while in CD-ROM mode!(PC: 0xC0BAC4)`  
`[libretro ERROR]   - Z80 port 0x0080 -> 0x00.`

The full logfile for Ironclad: [retroarch-log.txt](https://github.com/libretro/fbalpha/files/2306038/retroarch-log.txt)  
Fire Suplex: [retroarch-log.txt](https://github.com/libretro/fbalpha/files/2306128/retroarch-log.txt)

(also it says `[libretro WARN] [FBA] NeoGeo BIOS missing ...` but I have both `neogeo.zip` and `neocdz.zip` in my system folder, and excepted for the musics, I have no problem loading the games)

I tried the games with the standalone FBA (v0.2.97.43) and music is playing just fine.

**EDIT**  
Also no problem with games that are not using wav files, Bust-A-Move for example which is just iso/cue I have the music playing without issue.

**Comment by barbudreadmon** [comment] 2018-08-21 12:12
duplicate of #4

**Closed by barbudreadmon** 2018-08-21 12:12 UTC
