### ISSUE TITLE
Doing the Super Moves (command+2 buttons) doesn't work anymore in RetroArch Android

### ISSUE THREAD

**Issue by Immersion95** [libretro/fbalpha#129] opened 2019-02-07 15:54 UTC
Hi,

I launched Marvel Super Heroes (Jap, Eur, etc..) and I can't do the super moves anymore ! It works 1 out of 10 times.

I tried it on my Shield TV with the Shield controller and even with the Dual Shock 4 without luck.

Thanks for your help !

**Comment by barbudreadmon** [comment] 2019-02-07 15:58
Do you mean the macros don't work anymore ? If so that's a duplicate of #124 , and most likely this stuff will disappear from the core options soon (hopefully something to replace it will be done in RA).

**Comment by Immersion95** [comment] 2019-02-07 16:02
> Do you mean the macros don't work anymore ? If so that's a duplicate of #124 , and most likely this stuff will disappear from the core options soon (hopefully something to replace it will be done in RA).

Hi, yes the macros don't work too but it is not the same problem.
The problem here is that pressing 2 buttons simultaneously during a command doesn't work. I don't know if it's a problem with the Shield TV.

Exemple : Please try the "Shinkuu Hadoken move" with Spider-Man in Marvel Super Heroes.

**Comment by barbudreadmon** [comment] 2019-02-07 16:23
> Exemple : Please try the "Maximum Spider" with Spider-Man in Marvel Super Heroes.

It works for me, so that's definitely not an issue with the core, either that's an issue with your setup/controllers, or maybe an issue with RA on android. If you are confident your setup and controllers are working properly, you can try opening an issue about this in the RA repository. Closing.

**Closed by barbudreadmon** 2019-02-07 16:23 UTC
