### ISSUE TITLE
About (thndzonej.zip), picture mapping problem?

### ISSUE THREAD

**Issue by ji125443** [libretro/fbalpha#144] opened 2019-02-16 06:17 UTC
Test platform Android and Amlogic s905x, this game has a low frame rate
![thndzonej-190216-140011](https://user-images.githubusercontent.com/25021120/52895432-5982be80-31f5-11e9-88ec-abb3ce10c230.png)

**Comment by barbudreadmon** [comment] 2019-02-16 08:22
Thanks for the report, i think there might be a layer priority issue indeed.

**Comment by dinkc64** [comment] 2019-02-18 13:10
part1:
This game is very graphically intense, which would account for the low frame rate on lower systems.  The s905x runs at 1.5ghz (even though its advertised at 2ghz).  This game would run fine on my p4 3ghz though.

part2:  "not a bug but lack of (configured) hw needed to run it"
The game needs 32bpp video to be able to mix the alpha transparencies on that part, and later on in the level.  Without 32bpp, it can only show the part that is not mixed (the bottom part of "mission 1").

**Comment by barbudreadmon** [comment] 2019-02-18 14:08
@ji125443 
For the graphical glitch, you'll need to enable "Use 32-bits color depth when available" in core options
For improving speed, you might try increasing the value for "Frameskip" in core options

Closing.

**Closed by barbudreadmon** 2019-02-18 14:08 UTC

**Comment by dinkc64** [comment] 2019-02-18 14:16
just fyi, konami and taitof3 are the only systems that can mix alpha @ 16bit, but doing this @ 16bit is a bit more cpu-costly than doing so @ 32bit

**Comment by furiadeoso** [comment] 2019-02-18 15:19
«Use 32-bits color depth when available» could have an impact over cpu performance on games that are not needing it?

**Comment by barbudreadmon** [comment] 2019-02-18 15:28
A lot of driver are tagged as not compatible with 32bpp, those will automatically switch to 16bpp. For drivers compatible with both, the impact might be minor.

**Comment by dinkc64** [comment] 2019-02-18 23:45
It depends a lot on the system, cpu, video drivers, OS, etc.  It's hard to say without doing tests on each system.
