### ISSUE TITLE
Neogeo games do not load in core FBA Alpha

### ISSUE THREAD

**Issue by spielvan** [libretro/fbalpha#201] opened 2019-04-02 04:40 UTC
Today I was testing NeoGeo games in my android box with FBA ALPHA and some of the games were loaded and other times the same games did not load, or I would load and close before loading the most problematic roms that I remember were these:

Garou: Mark of the Wolves Metal Slug 4 and 5 TKOF, 99, 2000 and 2003

Apart from the NeoGeo games the FBA Alpha works well with games cps, konami, taito …

obs: a friend had the same problem, these games sometimes work and sometimes do not work, when it does not work the game will load the rom and close the retroarch, but if it works you play the game normally, and sometimes the same problem occurred in the games CPS3.

**Comment by barbudreadmon** [comment] 2019-04-02 06:40
I asked you several times for logs on the forum. Will you finally provide them or should i close ?

**Comment by spielvan** [comment] 2019-04-02 14:16
@barbudreadmon  No problems in logging, do I need to tell me how do I get the same ones in retroarch?

**Comment by barbudreadmon** [comment] 2019-04-02 14:24
https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-in-android

**Comment by spielvan** [comment] 2019-04-02 14:49
> https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-in-android

I never got the logcat, I thought that the retroarch itself generated the same, does it with this apps with it?

https://forum.xda-developers.com/android/apps-games/root-andy-log-spare-logging-scenarios-t2910334

**Comment by spielvan** [comment] 2019-04-02 15:02
@barbudreadmon https://gist.github.com/spielvan/bf4521a40f00c2a6edb314f1cdf07928

**Comment by barbudreadmon** [comment] 2019-04-02 15:28
I don't see anything related to fba or libretro in there, are you sure you launched the emulator while running this logcat thing ?

**Comment by spielvan** [comment] 2019-04-02 15:31
@barbudreadmon Sorry it was my fault, I had not loaded the retroarch, but was the logcat itself right? It's the first thing I do, can I leave the retroarch in the background to get the logcat? I'll get the logcat when the rom closes with the bug.

**Comment by barbudreadmon** [comment] 2019-04-02 15:33
I don't know, i don't play on smartphone, i use them as phone.

**Comment by spielvan** [comment] 2019-04-02 15:48
@barbudreadmon I also do not use the phone to play, I use a box android tv, MXIII-G TV BOX Android 5.1.1 1000M LAN US PLUG 2GB + 16GB 4K x 2K H.265 Decoding WiFi HDMI Amlogic S812 Quad Core 2.0 ghz GPU Octa Core ARM Mali-450 600mhz, Bluetooth 4.0

**Comment by spielvan** [comment] 2019-04-02 16:09
@barbudreadmon I took the log when the error appeared https://gist.github.com/spielvan/23d56e40cfc90ef861e15935dfab37af

**Comment by barbudreadmon** [comment] 2019-04-02 16:20
Start by updating your core, yours is at the very least several months old. It might be a temporary bug that got solved since then.

**Comment by spielvan** [comment] 2019-04-02 16:37
https://gist.github.com/spielvan/15c6793454eccdce3b59ed3a9934fb11

**Comment by barbudreadmon** [comment] 2019-04-02 17:06
I think the fact you are launching neogeo games 18 times in a row without closing retroarch even once is causing some ram shortage due to some memory leak, my opinion : 
- i'll check again, but i don't think there is a memory leak in fbalpha currently
- i'm sure there are in retroarch though (that would make this a retroarch bug), so launching games consecutively like that seems like a bad idea anyway
- changing games 18 times during a gaming session seems like a really forced way to produce this bug and not something that would happen in a normal use case

**Comment by spielvan** [comment] 2019-04-02 17:21
sometimes the bug happens in the first or second time that loads the rom, one thing I try is to close the core when I mute the game, instead of simply closing the retroarch and opening it again, because the android sometimes when the retroarch closes does not empty the temporary cache.

**Comment by barbudreadmon** [comment] 2019-04-02 19:15
> sometimes the bug happens in the first or second time that loads the rom

Like when you did a lot of other things previously or have other apps launched ? And after a reboot it takes a lot more tries ? That's another hint for the memory shortage. The fact the games you mentioned are all in the top 20 in terms of size in the fbalpha romset is yet another hint.
The fact you also have issues with temporary cache is yet another hint at the fact that you have an issue unrelated to the core.

Well, i tried to reproduce this to no avail, i checked for memory leaks but couldn't find any, anyway i decided to rewrite a few things related to unloading/loading games anyway to make it even more safe. The new version should be on the buildbot in a few hours. I hope it'll work because there is nothing else i can do.

**Comment by spielvan** [comment] 2019-04-02 22:33
@barbudreadmon Thanks for everything, I'll wait for this build to test.

**Comment by barbudreadmon** [comment] 2019-04-03 12:57
Did you try the new version ?

**Comment by spielvan** [comment] 2019-04-03 15:03
@barbudreadmon I just tried the last build and the bug continues, it's as if something did not allow the game to load, but sometimes it loads, I tried loading the TKOF2003 as soon as I called the box android tv and it did not load.

**Comment by barbudreadmon** [comment] 2019-04-03 15:18
Ok, it's not an issue with the core though, the code is perfectly safe and afaik it's working great with a lot of android devices. I've seen awfully bad reviews on amazon for this box, so i'll consider it's an issue with this box. Closing.

**Closed by barbudreadmon** 2019-04-03 15:18 UTC

**Comment by spielvan** [comment] 2019-04-03 16:05
@barbudreadmon I already use MX3-G with the retroarch since 2016, and I started using it I think it was in retroarch 1.4.0 if I'm not mistaken and these games worked normal I'm noticing instability in the retroarch in general and I put the retroarch builddo of yesterday and the historical stopped working in the ante biild yesterday normal, I will end up going back to retroarch 1.0.0.2 which for me was the most stable retroarch hehhehe. Thank you so much for everything and a hug.
