### ISSUE TITLE
tbowl - erratic inputs reset game

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#111] opened 2019-01-25 11:41 UTC
title.

**Comment by barbudreadmon** [comment] 2019-01-25 12:04
What do you mean exactly by "erratic inputs" ? I couldn't reproduce the issue.

**Comment by arnoldsecret** [comment] 2019-01-25 12:35
try repeatedly tapping the arrow keys.

**Comment by barbudreadmon** [comment] 2019-01-25 12:48
Ok, by hitting every arrow keys at the same time like a savage on my keyboard for a few seconds while in game, i managed to produce this reset. Seems like an issue in the driver itself, so i'm tagging @dinkc64

**Comment by dinkc64** [comment] 2019-01-25 13:53
some games crash or do weird things when left+right or up+down are pressed :)  I use a gamepad so I never catch these things.

**Comment by barbudreadmon** [comment] 2019-01-25 15:01
Thanks, i can't reproduce this issue anymore, closing :)

**Closed by barbudreadmon** 2019-01-25 15:01 UTC
Labels: FOR DINK, bug
