### ISSUE TITLE
Cannot access Unibios menu

### ISSUE THREAD

**Issue by ochief** [libretro/fbalpha#52] opened 2015-11-16 00:06 UTC
I am using the Win64 build of retroarch and cannot seem to access the unibios menu.  I believe it should be as simple as pressing A+B+C when you see the unibios menu come up.

In the Core Options
Neo Geo Mode = Unibios
Bios = Universe Bios ver. 3.1 (also tried with 3.0)

Am I missing something obvious?

I can however enter the unibios cheats menu by pressing START + SELECT during a game.

**Comment by AkimanBengus** [comment] 2016-02-20 09:47
Hello,

I haven't the solution for your problem but I wanted to clarify the use of the 'Neo Geo Mode' core option.

When selecting MVS, AES or UNIBIOS value, fba will choose the best bios available in the neogeo.zip in a particular order. (the UNIBIOS 3.1 before the 3.0 for example)
But if you want to choose a specific bios using the 'BIOS' core option/dipswitch you have to select the 'NeoGeo Mode' DIPSWITCH.
Also when you use the 'NeoGeo Mode' this is for all games but if you use the 'BIOS' dipswitch this game by game.

**Comment by fr500** [comment] 2016-05-15 17:48
I tried to go this route and it locked up and it's printing lots of this messages:
RetroArch [libretro DEBUG] ::   - 0x00FBE08F read (word, PC: 1EFBE08F)

**Comment by fr500** [comment] 2016-05-15 17:51
Oh, my issue, I guess I don't have the 3.2 bios, nevermind.
Ok so maybe we should relabel the core options?

Like this: 
NeoGeo Mode: Auto AES|Auto MVS|Auto Unibios|Manual
Manual Bios: AES|...etc

It should make things clear at least, I was confused too

**Comment by AkimanBengus** [comment] 2016-05-15 17:56
Ok, no problem, this can be renamed like this but for the last one (DIPSWITCH => Manual) I think it can be not enough clear that you also have to select the core option BIOS.

**Comment by fr500** [comment] 2016-05-15 17:59
Manual BIOS Selection then?

**Comment by AkimanBengus** [comment] 2016-05-15 18:03
ok for Manual :-)
But i think the @ochief problem is different, maybe it's related to the Win64 build.
It would be good to know if he has still the problem so we can close this issue.

**Comment by fr500** [comment] 2016-05-15 18:04
ABC works just fine so I think he may just be confused like I was

**Comment by sergiobenrocha2** [comment] 2016-12-03 20:32
This BIOS option should have some text in the menu to clarify that it's a per game option. It take sometime to find this thread and figure out it was normal behavior, not a bug.

**Comment by barbudreadmon** [comment] 2016-12-04 07:59
For the reminder, the per-game bios option is needed because some games won't boot with some bioses (fba codebase specify a per-game default bios which will work, and we use it for initializing this per-game bios option). 

So, any suggestion on what text we should use ?

**Comment by rossbeck** [comment] 2017-03-30 19:17
I know this is old, but I'm having the same issue.  On latest UniBios 3.2, able to easily get the in-game cheat menu with start+select, but I'm unable to access the main setup on startup with A+B+C.  Tried everything.  Has anyone been able to access this?

**Comment by ochief** [comment] 2017-07-10 15:38
I have not been around for months but the issue I had/have is exactly what Rossbeck is describing.  You should be able to access the Unibios menu by pressing whatever buttons you have mapped to [A]+[B]+[C] as per the Unibios documentation http://unibios.free.fr/howitworks.html

[Start]+[Select] does work but [A]+[B]+[C] does not.  This works in the standalone version of FBA.  Simply load a game like Windjammers, press the button combo and you get a specific Unibios menu that contains cheats etc. being able to do that through Retroarch/Lakka would be really useful

**Comment by barbudreadmon** [comment] 2017-10-20 06:08
Expect the "neogeo mode" core option to disappear in the near future, the reasons : 
- it doesn't exist in fba standalone, bios is set through the dipswitches in standalone, there is no alternative way.
- it is confusing with the dipswitch, and since it is a core option which apply the same setting to all games (unlike the dipswitch), sometimes it prevents a game to boot (some games only work with one kind of bios, and it is properly handled by the dipswitch), i had to fix one of those lately ( https://github.com/libretro/fbalpha/issues/138 ) and i'm pretty sure there are others (sometimes i see people reporting non-working neogeo games on various forums, and i'm 100% sure those games actually work)

I'll take a look if there is actually an issue with unibios when i'll look into it, but iirc, i never had any of the issues mentioned here, so that does look like a setup issue to me.

**Comment by Darknior** [comment] 2017-10-20 18:34
Thanks to report this issue.
I can't do [Start]+[Select] too
SELECT is my HOTKEY and mapped with all the buttons, and with START i exit to EmulationStation.
Is it possible to change this key combination ?
Thanks

**Comment by barbudreadmon** [comment] 2017-10-21 11:06
@rossbeck @ochief : i can confirm the [A]+[B]+[C] menu is accessible, you just need to go in the core option menu and set some shortcut for the "Diagnostic Input" core option.

@Darknior : i'm not 100% sure i can customize the [Start]+[Select] shortcut the same way as the [A]+[B]+[C] shortcut, but i'll take a look.

**Comment by Darknior** [comment] 2017-10-21 11:41
Yes thanks, sorry i found it yesterday, it works perfectly for me too.
Using START+A+B+Y because i use an x360 gamepad without C button :p

**Comment by barbudreadmon** [comment] 2017-10-22 09:52
I commited a few changes, actually i didn't remove the neogeo mode option, just made it safer and more explicit.
Also, it seems there is no way to customize the keys combinations for the unibios splash screen, sorry.

**Closed** 2018-01-14 15:44 UTC
Labels: enhancement
